name: new_project
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  #Icon
  cupertino_icons: ^1.0.2

  #State management
  get: ^4.6.5

  #Connectivity
  http: ^0.13.5

  #Database

  firebase_core: 1.23.0
  cloud_firestore:
  firebase_core_platform_interface: 4.5.1

  #firebase_core: ^1.23.0

  #Get user location
  location: ^4.4.0

  #Change app package name
  change_app_package_name: ^1.1.0

  #Responsive ui:
  sizer: ^2.0.15

  #Google fonts
  google_fonts: ^3.0.1

  #Pagination
  lazy_load_scrollview: ^1.3.0

  #Maps
  syncfusion_flutter_maps: ^20.3.58




  background_locator:
   git:
    url: https://github.com/caiobraga/background_locator



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

